ds4_twist:
  ros__parameters:
    stamped: false
    inputs:
      linear:
        x: axis_left_y + button_dpad_up - button_dpad_down
        y: axis_left_x + button_dpad_left - button_dpad_right
        # z:
      angular:
        # x:
        # y:
        z: axis_right_x
    scales:
      linear:
        # Default scale is 1.0
        x: 0.25
        y: 0.20
        # z:
      angular:
        # x:
        # y:
        z: 1.70